name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=omerfeyzioglu_Spring-Boot-Web-App \
            -Dsonar.organization=omerfeyzioglu_Spring-Boot-Web-App \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${74245f98178f4843437f1d8e6deeff5946107b58}
